{% set name = "dvc-http" %}
{% set version = "2.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a5feebc65a9f0bfc085a0253a02ac4952bede3d42635c4ef2ac51b5833b69b3a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm >=6.3.1
  run:
    - python >=3.8
    - dvc
    - fsspec
    - aiohttp-retry >=2.5.0

test:
  imports:
    - dvc_http
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/iterative/dvc-http
  summary: HTTP(s) plugin for DVC
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - efiop
    - shcheklein
